### PR TITLE
Feature: Set Filter Labels in Template

### PR DESCRIPTION
**Pull request by benloh**
Addresses #276 

The Filter labels for "Fade", "Remove", and "Focus" functions, along with their accompanying help text, can now be defined via a project template.

The fields that can be edited are:

* filterFade
* filterReduce
* filterFocus
* filterFadeHelp
* filterReduceHelp
* filterFocusHelp

Other Notes
* If an older template does not define these values, default values are drawn from `FilterEnums.js`
* The default values will not be saved to the older template file unless the user explicitly saves the template.  (If it is not saved, it will be automatically converted each time the project opens).

#### Developer Notes

* Template Migration -- Template migration is now an explicit function in `server-database.js`.  Any future changes to `template-schema.js` should also add migration methods here.
* Template loading is now asynchronous -- Template loading should have been asynchronous from the start, but we were able to gloss over it.  However, asynchronous support is needed for migration and validation.

### CODE REVIEW

**Comment by jdanish** [comment]
To explicitly save does one just edit something else and then save?

**Comment by benloh** [comment]
> To explicitly save does one just edit something else and then save?

Actually all you have to do is click More > Edit Template > Edit Current Template and then click Save.  You don't have to change anything.

I had been considering setting a flag when we do the migration and asking the user if they would like to update their template.  Maybe only for admin user?

**Review by jdanish — APPROVED** [review]
Look good to me. Thanks!

**Comment by benloh** [comment]
Merging.  We'll rely on the use selecting save themselves.

**Pull request merged**
