### PR TITLE
Filter Feature

### PR DESCRIPTION
**Pull request by benloh**
This implements #167.

Branch: `dev-bl/filter`

This introduces "Highlighting" and "Filtering" as separate but related features.

Whimsical [graph data flow diagram](https://whimsical.com/d3-data-flow-B2tTGnQYPSNviUhsPL64Dz)

# To Test

1. `git fetch; git checkout dev-bl/filter`
2. `./nc.js --dataset=<yourdataset` -- Open a dataset that has a number of nodes and edges.
3. Click "Highlight/Filter" tab
4. Select Label: "contains".
5. Type in a seach value, e.g. "the"
6. The system should fade away any nodes that do not contain "the" -- note edges should fade too
7. Click the "Filter" tab.
8. The system should redraw, this time removing any nodes that do not contain "the".

The idea here is that the highlight/filter form acts the same across both conditions.  This way you can easily toggle back and forth between fading (highlighting) and removing (filtering).

9. Click the "Graph" tab.
10. You should see a summary of the current highlight/filter setting in a blue bar under "Graph".  It should indicate whether you have highlight or filter active.
11. You should be able to add and edit nodes and edges.

NOTE if you add a new node that is filtered out, it won't display.

---

As noted in #167, there are still a number of related features that are outstanding.

### CODE REVIEW

**Comment by benloh** [comment]
@jdanish @kalanicraig Here's a first pass at highlighting/filtering.  There's still more to be done (see #167), but I believe this is functional enough to play with.  Please give it a whirl and see how it feels.

**Comment by jdanish** [comment]
Sweet!! Looks really good. 

Three minor things I noticed at a glance that I am sure on your list but will note just in case:

1) the message about what is being filtered on is always visible but presumably would go away after clicking to clear them
2) the options that have drop-down menus (type) have no way of being unselected so that appears as a filter criteria even though it's not being applied
3) an old issue that when you login, the graph gets shifted up and two the left for some reason

Looking good!

**Comment by jdanish** [comment]
FYI, since my server is only for testing right now, I went ahead and updated it so we can play. Feel free to hop on as well: http://134.209.73.52/l

The management password is the default.

Looking good!

**Comment by jdanish** [comment]
Also just noticed if you type something in a filter and then hit enter it redirects to a page with an error.

**Comment by benloh** [comment]
# TO DO
* [ ] Filter summary message does not clear if there are no filters
* [ ] Selection dropdown values are always selected
* [ ] After clearing filters, node sizes are not restored
* [ ] Type in filter, hit enter -- error?

**Comment by benloh** [comment]
@jdanish NodeTables and EdgeTables now show highlighted/filtered status.  If highlighted, we use the same transparency value as defined in the filter.  If removed (filtered) we show the item in red.

**Comment by jdanish** [comment]
Thanks! This appears to function as advertised and is very cool.

It does have me wondering whether the filter panel would be easier to use if it was a popup that you could move around because it feels counter-intuitive to have to tab from it to others.

I need to talk to Kalani more, but just floating that. Any thoughts?

**Comment by benloh** [comment]
#172 should be fixed now.

**Comment by benloh** [comment]
> It does have me wondering whether the filter panel would be easier to use if it was a popup that you could move around because it feels counter-intuitive to have to tab from it to others.

I find the problem with popups is you spend a lot of time fiddling with them and moving them out of the way all the time. That said, the current setup does eat up a LOT of space.  

Two ideas:
1. Tighten up the spacing for now.  It's not as efficient as it can be.
2. Wait until the Finder-like-search rewrite when the whole tab panel will be smaller.

It shouldn't be too hard to convert it to a popup if we have to, though we'd probably want to figure out a new mechanism for opening it then, since it should no longer be a tab panel.

**Comment by jdanish** [comment]
For me, what makes it not work as a tab is that if you are looking at the tables, you need to pop back and forth. Ideally you could see the graph and table while changing the filters. Hence the popup idea. I honestly don't mind moving popups, but Kalani agrees with you. 

Anyhow, Kalani is going to check with Ann who has a lot more experience with all of the network visualization apps, and then we'll come back with a suggestion or decision to wait.

Thanks!

**Comment by benloh** [comment]
Sounds like a good idea.  If you have screenshots we can steal ideas.  Things have been going pretty fast, so I think we can spend the time to design a nice UI for it.

**Comment by benloh** [comment]
Marking this done and ready to merge.

**Pull request merged**
